-- 코드를 입력하세요
/*
SELECT 
    OFF.OFFLINE_SALE_ID
FROM ONLINE_SALE ON , 
    (SELECT '' AS USER_ID,
     OFFLINE_SALE_ID,
     PRODUCT_ID,
     SALES_AMOUNT,
     SALES_DATE
     FROM OFFLINE_SALE) OFF
WHERE ON.PRODUCT_ID = OFF.PRODUCT_ID
AND ON.SALES_DATE >= TO_DATE('2022-03-01')
    AND ON.SALES_DATE <= TO_DATE('2022-03-31')
AND OFF.SALES_DATE >= TO_DATE('2022-03-01')
    AND OFF.SALES_DATE <= TO_DATE('2022-03-31')
*/

WITH A AS(
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM ONLINE_SALE
WHERE SALES_DATE
BETWEEN TO_DATE('2022-03-01','YYYY-MM-DD')
AND TO_DATE('2022-03-31','YYYY-MM-DD')),
B AS (
    SELECT NULL AS USER_ID,
     OFFLINE_SALE_ID,
     PRODUCT_ID,
     SALES_AMOUNT,
     SALES_DATE
     FROM OFFLINE_SALE 
     WHERE SALES_DATE 
     BETWEEN TO_DATE('2022-03-01','YYYY-MM-DD')
     AND TO_DATE('2022-03-31','YYYY-MM-DD'))
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM A
UNION
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM B
