-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(SUM(R.REVIEW_SCORE)/COUNT(R.REVIEW_ID),2) AS REVIEW_SCORE
FROM REST_REVIEW R
INNER JOIN REST_INFO I
ON R.REST_ID = I.REST_ID
WHERE SUBSTR(I.ADDRESS,1,2) = '서울'
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY ROUND(SUM(R.REVIEW_SCORE)/COUNT(R.REVIEW_ID),2) DESC, I.FAVORITES DESC
