-- 코드를 입력하세요
SELECT 
    EXTRACT(year FROM SALES_DATE) AS YEAR,
    EXTRACT(month FROM SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE A , USER_INFO B
WHERE GENDER IS NOT NULL
AND A.USER_ID = B.USER_ID
GROUP BY
    EXTRACT(year FROM SALES_DATE),
    EXTRACT(month FROM SALES_DATE),
    GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER