-- 코드를 입력하세요
SELECT (CASE
       WHEN TO_CHAR(DATETIME,'HH24') LIKE '0%'
       THEN SUBSTR(TO_CHAR(DATETIME,'HH24'),2,1)
       ELSE TO_CHAR(DATETIME,'HH24')
       END) AS HOUR,
    COUNT(*) AS TOTAL_NUM
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24')  BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24') ASC