WITH T1 AS
(
    SELECT  CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE 1=1 
       AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
     GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) 
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH, A.CAR_ID
     , COUNT(*) RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 INNER JOIN T1 B
    ON 1=1
   AND B.CAR_ID = A.CAR_ID
 GROUP BY TO_CHAR(START_DATE, 'MM'), A.CAR_ID 
 HAVING 1=1
    AND COUNT(*) <> 0
    AND TO_CHAR(START_DATE, 'MM') BETWEEN 8 AND 10
  ORDER BY TO_CHAR(START_DATE, 'MM'), A.CAR_ID DESC