SELECT DISTINCT A.CAR_ID
FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN CAR_RENTAL_COMPANY_CAR B
ON A.CAR_ID = B.CAR_ID
WHERE SUBSTR(TO_CHAR(A.START_DATE,'YYYYMM'),5,2) = '10'
AND   B.CAR_TYPE = '세단'
ORDER BY 1 DESC