SELECT '/home/grep/src/'||AA.BOARD_ID||'/'||AA.FILE_ID||AA.FILE_NAME||AA.FILE_EXT AS "FILE_PATH"
FROM(SELECT B.BOARD_ID, 
				B.FILE_ID, 
				B.FILE_EXT, 
				B.FILE_NAME, 
				RANK() OVER (ORDER BY A.VIEWS DESC) AS "순위"
       FROM USED_GOODS_BOARD A, USED_GOODS_FILE B
      WHERE A.BOARD_ID = B.BOARD_ID
    ) AA
WHERE "순위" = 1
ORDER BY AA.FILE_ID DESC